openapi: 3.0.3

info:
  description: This is the API model for CoEpi Server
  version: 0.3.0
  title: CoEpi Server
  license:
    name: MIT License
    url: https://github.com/Co-Epi/data-models/blob/master/LICENSE

paths:
  /cenreport:
    post:
      summary: Submit symptom or infection report
      description: Users submit symptom / infection reports and reveal the secret CENKey in their application

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                report:
                  type: string
                  format: byte # base64 encoded data
                  description: Content of the infection report. Example, symptoms
                cenKeys:
                  type: array
                  items:
                    $ref: '#/components/schemas/CenKey'
                  minItems: 1
                  maxItems: 100 # TODO: Discuss appropriate value
                  uniqueItems: true
              example:
                report: "c2V2ZXJlIGZldmVyLGNvdWdoaW5nLGhhcmQgdG8gYnJlYXRoZQ=="
                cenKeys: [ "2cb87ba2f39a3119e4096cc6e04e68a8","4bb5c242916d923fe3565bd5c6b09dd3" ]
              required:
              - report
              - cenKeys

      responses:
        '200':
          description: The report was submitted successfully
        '400':
          description: Request Parameter Invalid # TBD
        '500':
          description: Internal Server Error


    get:
      summary: Returns a list of reports generated for a given day and batch number.

      description: Batch number is a positive integer value that corresponds to all reports generated during a
          fixed time interval, where the first interval starts at 1. The fixed-interval length is currently 6 hours.
          Example, batch 1 for date 2020-04-04 will return all reports generated from
          2020-04-04T00:00:00 UTC to 2020-04-04T06:00:00 UTC, inclusive.

      parameters:
      - in: query
        name: date
        description: Date in RFC3339 standard in UTC, without the time component. If not provided, default value of today's
            date is used.
        required: false
        schema:
          type: string
          format: date
        example: 2020-05-04
      - in: query
        name: batchNumber
        description: Batch number is a positive integer
          value that corresponds to all reports generated during a fixed time interval, where the first interval starts
          at 1. If not provided, then the latest batch number for the specified date (or current date, if not specified)
          is used.
        required: false
        schema:
          type: integer
        example: 2
      responses:
        '200':
          description: List of infection/symptom reports generated during the specified date and batch number
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
        '400':
          description: Request Parameter Invalid # TBD
        '500':
          description: Internal Server Error


# https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md
components:
  schemas:
    CenKey:
      description: Contact Event Number (CEN) published by the mobile device
      type: string
      minLength: 5 #TODO: Discuss appropriate value
      maxLength: 100 #TODO: Discuss appropriate value and also a possibly an expected pattern
      example: "67f48de38f35c231e34e533649ecbfeb"

    Report:
      type: object
      description: Infection report representing symptoms and/or positive infection incident
      properties:
        reportId:
          type: string
          description: Unique Identifier of the infection report
          minLength: 1 #TODO: Discuss appropriate value
          maxLength: 100 #TODO: Discuss appropriate value and also a possibly an expected pattern (guid ?)
        report:
          type: string
          description: Content of the infection report consisting of symptoms and/or positive infection incident. Base64 encoded
          format: byte # base64 encoded data
          minLength: 1
          maxLength: 10000
        cenKeys:
          type: array
          description: CEN Keys belonging to the device that publushed the report
          items:
            $ref: '#/components/schemas/CenKey'
      example:
        reportId: "6d68785abd6f99ea646fd7c775a14a36f7cec7635a76d3b5554908c6c3a09af5"
        report: "c2V2ZXJlIGZldmVyLGNvdWdoaW5nLGhhcmQgdG8gYnJlYXRoZQ=="
        cenKeys: [ "2cb87ba2f39a3119e4096cc6e04e68a8","4bb5c242916d923fe3565bd5c6b09dd3" ]
